# ~/.config/matugen/templates/fzf-colors.zsh
# Dynamically generated by Matugen

export FZF_DEFAULT_OPTS="--ansi --preview 'bat --color=always --style=header,grid --line-range :300 {}' \
--color=fg:{{colors.on_surface.default.hex}},bg:{{colors.surface.default.hex}},hl:{{colors.primary.default.hex}} \
--color=fg+:{{colors.on_surface.default.hex}},bg+:{{colors.surface_container_highest.default.hex}},hl+:{{colors.primary.default.hex}} \
--color=info:{{colors.tertiary.default.hex}},prompt:{{colors.primary.default.hex}},pointer:{{colors.primary.default.hex}} \
--color=marker:{{colors.secondary.default.hex}},spinner:{{colors.secondary.default.hex}},header:{{colors.secondary.default.hex}}"
