{
    "metadata": {
        "name": "Matugen Dynamic",
        "revision": 1
    },
    "editor-colors": {
        "BackgroundColor": "{{colors.surface.default.hex}}",
        "BracketMatching": "{{colors.surface_container_highest.default.hex}}",
        "CodeFolding": "{{colors.secondary_container.default.hex}}",
        "CurrentLine": "{{colors.surface_container_low.default.hex}}",
        "CurrentLineNumber": "{{colors.on_surface.default.hex}}",
        "IconBorder": "{{colors.surface.default.hex}}",
        "IndentationLine": "{{colors.outline_variant.default.hex}}",
        "LineNumbers": "{{colors.outline.default.hex}}",
        "SearchHighlight": "{{colors.primary_container.default.hex}}",
        "Separator": "{{colors.outline_variant.default.hex}}",
        "TextSelection": "{{colors.primary_container.default.hex}}"
    },
    "text-styles": {
        "Normal": {
            "text-color": "{{colors.on_surface.default.hex}}"
        },
        "Keyword": {
            "bold": "true",
            "text-color": "{{colors.primary.default.hex}}"
        },
        "Function": {
            "text-color": "{{colors.secondary.default.hex}}"
        },
        "String": {
            "text-color": "{{colors.tertiary.default.hex}}"
        },
        "Comment": {
            "italic": "true",
            "text-color": "{{colors.outline.default.hex}}"
        },
        "DataType": {
            "text-color": "{{colors.secondary_fixed_dim.default.hex}}"
        },
        "Constant": {
            "text-color": "{{colors.primary.default.hex}}"
        },
        "ControlFlow": {
            "bold": "true",
            "text-color": "{{colors.primary.default.hex}}"
        }
    }
}
