# ~/.config/kitty/kitty.conf
# Clean, minimal Kitty configuration

# --- Fonts ---
font_family         JetBrainsMono Nerd Font
bold_font           auto
italic_font         auto
bold_italic_font    auto
font_size           12.0
disable_ligatures   cursor
undercurl_style     thin-sparse

# --- Cursor & Animations ---
cursor_shape                beam
cursor_shape_unfocused      unchanged
cursor_beam_thickness       1.5
cursor_blink_interval       0.75 ease-in-out
pointer_shape_when_grabbed  beam
cursor_trail                1
cursor_trail_decay          0.1 0.4

# --- Scrollback & Scrollbar ---
scrollback_lines            5000
scrollbar                   never

# --- Window Layout & Padding ---
window_padding_width        	12
background_opacity          	0.75
confirm_os_window_close     	0
tab_bar_style					fade
tab_bar_align					center
tab_bar_show_new_tab_button		yes

# --- Miscellaneous ---
enable_audio_bell       no

# --- Keybindings ---
map ctrl+backspace send_text all \x17


# --- Theme Include ---
include themes/Matugen.conf
